###################  项目启动端口  ###################
server:
  port: 8080

spring:
  datasource:
    primaryDatasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.10.86.182:1521/idpsit
      username: zyb_user
      password: zyb_user
    apiDatasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.10.86.182:1521/idpsit
      username: zyb_user
      password: zyb_user
    ruleEngineDatasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.10.86.182:1521/idpsit
      username: zyb_user
      password: zyb_user
    filters: log4j,wall,mergeStat
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小

logging:
  config: classpath:logback-release.xml
  
